name:                hsfun
version:             0.1.0.0
github:              "githubuser/hsfun"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hsfun#readme>

dependencies:
- base >= 4.7 && < 5
- http-conduit
- yaml
- bytestring
- aeson
- split
- time
- hxt
- hxt-xpath >= 9.1.2.2
- HandsomeSoup
- base64-bytestring
- case-insensitive
- text
- authenticate-oauth
- connection
- conduit
- primitive
- containers
- regex-tdfa
- extra
- process
- transformers
- vector

library:
  source-dirs: src

executables:
  twcli:
    main:                Main.hs
    source-dirs:         app/twcli
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsfun
  sysmon:
    main:                Main.hs
    source-dirs:         app/sys_mon
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsfun
  cowinbob:
    main:                Main.hs
    source-dirs:         app/cowinbob
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsfun

tests:
  hsfun-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsfun
